services:
  nginx:
    image: nginx:alpine
    container_name: scangenie_ui_nginx
    ports:
      - "82:80"
    volumes:
      - ./nginx-scangenie_ui.conf:/etc/nginx/nginx.conf
      - ./:/var/www  # Mount the dist folder from your local machine to the container
    depends_on:
      - nodejs
    restart: always
    networks:
      - app-network

  nodejs:
    image: node:16-alpine
    container_name: scangenie_ui
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules  # Hindari overwrite node_modules
    command: ["npm", "run", "serve"]
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
