events {
    worker_connections 1024;  # Jumlah koneksi maksimum per worker
}

http {
    server {
        listen 80;
        server_name localhost;

        root /var/www/dist;  # Ubah root ke folder 'dist' yang dihasilkan oleh 'npm run build'
        index index.html;

        location / {
            try_files $uri $uri/ /index.html?$query_string;
        }

        # Exclude static files like favicon.ico, .css, .js, etc. from being redirected
        location = /favicon.ico {
            log_not_found off;  # Optional: turn off logging for missing favicon.ico
            access_log off;     # Optional: turn off access logging for favicon.ico
        }

        location ~ \.js$ {
            add_header Cache-Control "public, max-age=31536000, immutable";
        }

        location ~ \.css$ {
            add_header Cache-Control "public, max-age=31536000, immutable";
        }

        location ~ /\.ht {
            deny all;
        }

        # Handle other static files
        location ~* \.(jpg|jpeg|png|gif|css|js|woff|woff2|eot|ttf|svg|ico)$ {
            add_header Cache-Control "public, max-age=31536000, immutable";
        }
    }
}
